ZealEducation/Controllers/TimeTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;

namespace ZealEducationManagement.Controllers
{
    public class TimeTablesController : Controller
    {
        private ZealEducationMgtDbEntities db = new ZealEducationMgtDbEntities();
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        // GET: TimeTables
        public ActionResult Index()
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            var timeTables = db.TimeTables.Include(t => t.Class).Include(t => t.Room).Include(t => t.Subject).Include(t => t.Teacher);
            return View(timeTables.ToList());
        }

        // GET: TimeTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        // GET: TimeTables/Create
        public ActionResult Create()
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            //ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassName");
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomID", "RoomName");
            //ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName");
            ViewBag.TeacherID = new SelectList(db.Teachers, "TeacherID", "TeacherName");
            ViewBag.ClassList = new SelectList(GetClassList(), "ClassID", "ClassName");
            return View();
        }

        public List<Class> GetClassList()
        {
            //String current = DateTime.Now.ToShortDateString();
            //DateTime currentDate = Convert.ToDateTime(current);
            var timeTableL = db.TimeTables.Select(y => y.ClassID);
            if (timeTableL == null)
            {

                List<Class> ClassList = db.Classes.Where(c => !timeTableL.Contains(c.ClassID)).ToList();
                return ClassList;
            }
            else
            {
                List<Class> ClassList = db.Classes.ToList();
                return ClassList;
            }
            
        }

        public JsonResult GetSubjectList(string ClassID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            if (ClassID == "")
            {
                return null;
            }
            else
            {
                //var FacultyID = GetClassList().FirstOrDefault(x => x.ClassID == ClassID).FacultyID;
                //List<Subject> SubjectList = db.Subjects.Where(x => x.FacultyId == FacultyID).ToList();
                List<Subject> SubjectList = db.ClassSubjects.Where(x => x.ClassID == ClassID && x.Status == true).Select(y => y.Subject).ToList();
                return Json(SubjectList, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetTeacherList(string SubjectID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            if (SubjectID == "")
            {
                return null;
            }
            else
            {
                List<Teacher> TeacherList = db.MultiSubjectTeachers.Where(x => x.SubjectID == SubjectID).Select(y => y.Teacher).ToList();
                return Json(TeacherList, JsonRequestBehavior.AllowGet);
            }
        }
        // Kiểm tra trùng lặp
        public bool TimeTableCheck(String ClassID, String TeacherID, String SubjectID, TimeSpan TimeIn, TimeSpan TimeOut, DateTime Day, int RoomId)
        {
            List<TimeTable> TimeTableList = db.TimeTables.Where(x => x.Day == Day).ToList();
            bool check = true;
            DateTime currentDate = DateTime.Now;
            TimeSpan currentTime = currentDate.TimeOfDay;
            TimeSpan EndTime = new TimeSpan(19, 0, 0);
            int result = DateTime.Compare(currentDate, Day);
            if (result >= 0 && currentTime > TimeIn && TimeIn < EndTime)
            {
                TempData["error"] = "It's past time to schedule class";
                check = false;
            }
            else
            {
                foreach (var item in TimeTableList)
                {
                    if (ClassID == item.ClassID)
                    {
                        TempData["error"] = "A class can only take one lesson in a day";
                        check = false; 
                        break;
                    }
                    else
                    {
                        if (TimeIn < item.TimeIn && TimeOut > item.TimeOut || TimeOut > item.TimeIn && TimeOut <= item.TimeOut || TimeIn >= item.TimeIn && TimeOut < item.TimeOut)
                        {
                            if (RoomId == item.RoomId)
                            {
                                TempData["error"] = "This Room has been used for this time";
                                check = false;
                                break;
                            }
                            else if (TeacherID == item.TeacherID)
                            {
                                TempData["error"] = "This Teacher has been scheduled for this time";
                                check = false;
                                break;
                            }
                            else
                            {

                                check = true;
                                break;
                            }
                        }
                        else
                        {
                            check = true;
                            break;
                        }
                    }
                }
            }

            return check;
        }



        // POST: TimeTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TimeID,ClassID,TeacherID,SubjectID,TimeIn,TimeOut,Day,RoomId,IsAcvite,Isfinished")] TimeTable timeTable)
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                if (TimeTableCheck(timeTable.ClassID, timeTable.TeacherID, timeTable.SubjectID, timeTable.TimeIn, timeTable.TimeOut, timeTable.Day, timeTable.RoomId))
                {
                    timeTable.IsAcvite = true;
                    timeTable.Isfinished = false;
                    db.TimeTables.Add(timeTable);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ClassList = new SelectList(GetClassList(), "ClassID", "ClassName");
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomID", "RoomName", timeTable.RoomId);
                    //ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", timeTable.SubjectID);
                    //ViewBag.TeacherID = new SelectList(db.Teachers, "TeacherID", "TeacherName", timeTable.TeacherID);
                    return View(timeTable);
                }
            }
            else
            {
                TempData["error"] = "validationsummary field is required";
                ViewBag.ClassList = new SelectList(GetClassList(), "ClassID", "ClassName");
                ViewBag.RoomId = new SelectList(db.Rooms, "RoomID", "RoomName", timeTable.RoomId);
                //ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", timeTable.SubjectID);
                //ViewBag.TeacherID = new SelectList(db.Teachers, "TeacherID", "TeacherName", timeTable.TeacherID);
                return View(timeTable);
            }
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        // GET: TimeTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClassID = new SelectList(db.Classes, "ClassID", "ClassName", timeTable.ClassID);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomID", "RoomName", timeTable.RoomId);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", timeTable.SubjectID);
            ViewBag.TeacherID = new SelectList(db.Teachers, "TeacherID", "TeacherName", timeTable.TeacherID);
            return View(timeTable);
        }

ZealEducation/Views/TimeTables/Create.cshtml
@model DataAccess.TimeTable

@{
    ViewBag.Title = "Create";
}
<script src="~/Scripts/toastr.min.js"></script>
<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="info" value="@TempData["info"]" />
<input type="hidden" id="info" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />
<!-- Breadcubs Area Start Here -->
<div class="breadcrumbs-area">
    <h3>Time Tables</h3>
    <ul>
        <li>
            @Html.ActionLink("Back to List", "Index")
        </li>
        <li>Add Time Table</li>
    </ul>
</div>
<!-- Breadcubs Area End Here -->
<!-- Admit Form Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>Add New Time Table</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-expanded="false">...</a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-times text-orange-red"></i>Close
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs text-dark-pastel-green"></i>Edit
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-redo-alt text-orange-peel"></i>Refresh
                    </a>
                </div>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal new-added-form">
                <div class="row">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Class Name *</label>
                        <div>
                            @if (ViewBag.ClassList != null)
                            {
                                @Html.DropDownListFor(m => m.ClassID, (IEnumerable<SelectListItem>)ViewBag.ClassList as SelectList, "-- Select Class --", new { @class = "select2 form-control" });

                            }

                            @*@Html.DropDownList("ClassID", null, htmlAttributes: new { @class = "form-control" })*@
                            @Html.ValidationMessageFor(model => model.ClassID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Subject Name *</label>
                        <div>
                            @*@Html.DropDownListFor(m => m.SubjectID, new SelectList(""), "-- Select Subject --", new { @class = "form-control" })*@
                            <select id="SubjectID" name="SubjectID" class="select2 form-control">
                                <option value="">Select Subject</option>
                            </select>
                            @*@Html.DropDownList("SubjectID", null, htmlAttributes: new { @class = "form-control" })*@
                            @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Teacher Name *</label>
                        <div>
                            <select id="TeacherID" name="TeacherID" class="select2 form-control">
                                <option value="">Select Teacher</option>
                            </select>
                            @*@Html.DropDownList("TeacherID", null, htmlAttributes: new { @class = "form-control" })*@
                            @Html.ValidationMessageFor(model => model.TeacherID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Day *</label>
                        <div>
                            @*@Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control" } })*@
                            <input type="text" id="Day" name="Day" placeholder="dd/mm/yyyy" class="form-control air-datepicker DayTimeTbl"
                                   data-position='bottom right' autocomplete="off">
                            <i class="far fa-calendar-alt"></i>
                            @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Time In *</label>
                        <div>
                            <input type="text" id="TimeIn" name="TimeIn" class="form-control start-time air-datepicker" data-position='bottom right' data-timepicker="true" autocomplete="off">
                            <i class="far fa-clock"></i>
                            @*@Html.EditorFor(model => model.TimeIn, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.ValidationMessageFor(model => model.TimeIn, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Time Out *</label>
                        <div>
                            <input type="text" id="TimeOut" name="TimeOut" class="form-control end-time air-datepicker" data-position='bottom right' data-timepicker="true" autocomplete="off">
                            <i class="far fa-clock"></i>
                            @*@Html.EditorFor(model => model.TimeOut, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.ValidationMessageFor(model => model.TimeOut, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        <label>Room Name *</label>
                        <div>
                            @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-12 form-group mg-t-8">
                        <button type="submit" value="Create" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                        <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                    </div>
                </div>
            </div>
        }

    </div>
</div>



<script>
    //$(document).ready(function () {
    //    $("#ClassID").change(function () {
    //        var classID = $("#ClassID").val();
    //        $.ajax({
    //            type: "post",
    //            url: "/TimeTables/GetSubjectList?ClassID=" + classID,
    //            contentType: "html",
    //            success: function (response) {
    //                $("#SubjectID").empty();
    //                $("#SubjectID").append(response);
    //            }
    //        })
    //    })
    //})

    $(document).ready(function () {
        $("#ClassID").change(function () {
            $.get("/TimeTables/GetSubjectList", { ClassID: $("#ClassID").val() }, function (data) {
                $("#SubjectID").empty();
                $("#SubjectID").append("<option value=''>-- Select Subject --</option>");
                $.each(data, function (index, row) {
                    $("#SubjectID").append("<option value='" + row.SubjectID + "'>" + row.SubjectName + "</option>");
                })
            })
        })
    })

    $(document).ready(function () {
        $("#SubjectID").change(function () {
            $.get("/TimeTables/GetTeacherList", { SubjectID: $("#SubjectID").val() }, function (data) {
                $("#TeacherID").empty();
                $("#TeacherID").append("<option value=''>-- Select Teacher --</option>");
                $.each(data, function (index, row) {
                    $("#TeacherID").append("<option value='" + row.TeacherID + "'>" + row.TeacherName + "</option>");
                })
            })
        })
    })
</script>
<script>
    $(function () {
        if ($('#success').val()) {
            displayMessage($('#success').val(), 'success');
        }
        if ($('#info').val()) {
            displayMessage($('#info').val(), 'info');
        }
        if ($('#warning').val()) {
            displayMessage($('#warning').val(), 'warning');
        }
        if ($('#error').val()) {
            displayMessage($('#error').val(), 'error');
            $('#ClassID').prop('selectedIndex', 0);
        }
    });
    var displayMessage = function (message, msgType) {
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-top-right",
            "onClick": null,
            "showDuration": "3000",
            "hideDuration": "1000",
            "timeOut": "8000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
        toastr[msgType](message);
    };
</script>

ZealEducation/Views/TimeTables/Delete.cshtml
@model DataAccess.TimeTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TimeTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TimeIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.TeacherName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ZealEducation/Views/TimeTables/Details.cshtml
@model DbAccess.TimeTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TimeTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TimeIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.frametime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.frametime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Room.RoomName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.RoomName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.TeacherName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TimeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ZealEducation/Views/TimeTables/Index.cshtml
@model IEnumerable<DataAccess.TimeTable>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<!-- Breadcubs Area Start Here -->
<div class="breadcrumbs-area">
    <h3>TimeTables</h3>
    <ul>
        <li>
            <a href="#">Home</a>
        </li>
        <li>All TimeTable</li>
    </ul>
</div>
<!-- Breadcubs Area End Here -->
<!-- Student Table Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>All TimeTables Data</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-expanded="false">...</a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-times text-orange-red"></i>Close
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs text-dark-pastel-green"></i>Edit
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-redo-alt text-orange-peel"></i>Refresh
                    </a>
                </div>
            </div>
        </div>
        <form class="mg-b-20">
            <div class="row gutters-8">
                <div class="col-4-xxxl col-xl-4 col-lg-3 col-12 form-group">
                    <input type="text" placeholder="Search by Name ..." class="form-control">
                </div>
                <div class="col-4-xxxl col-xl-3 col-lg-3 col-12 form-group">
                    <input type="text" placeholder="Search by Class ..." class="form-control">
                </div>
                <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                    <button type="submit" class="fw-btn-fill btn-gradient-yellow">SEARCH</button>
                </div>
                <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                    <a href="@Url.Action("Create", "TimeTables")" class="btn-fill-lmd radius-30 text-light shadow-dark-pastel-green bg-dark-pastel-green">Create</a>
                </div>
            </div>
        </form>
        <div class="table-responsive">
            <table class="table display data-table text-nowrap">
                <tr>
                    <th>
                        STT
                    </th>
                    <th>
                        Class Name
                    </th>
                    <th>
                        Subject Name
                    </th>
                    <th>
                        Teacher Name
                    </th>
                    <th>
                        Room Name
                    </th>
                    <th>
                        Time In
                    </th>
                    <th>
                        Time Out
                    </th>
                    <th>
                        Day
                    </th>
                    <th>
                        Is Acvite
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @i
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Class.ClassName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subject.SubjectName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Teacher.TeacherName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Room.RoomName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Day)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TimeIn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TimeOut)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsAcvite)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.TimeID })
                        </td>
                    </tr>
                    i++;
                }

            </table>
        </div>
    </div>
</div>
<!-- Student Table Area End Here -->