ZealEducation/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;

namespace ZealEducation.Controllers
{
    public class GradesController : Controller
    {
        private ZealEducationMgtDbEntities db = new ZealEducationMgtDbEntities();

        // GET: Grades
        public ActionResult Index()
        {
            var grades = db.Grades.Include(g => g.GradeType).Include(g => g.Student).Include(g => g.Subject);
            return View(grades.ToList());
        }

        // GET: Grades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            return View(grade);
        }

        // GET: Grades/Create
        public ActionResult Create()
        {
            ViewBag.ClassId = new SelectList(db.Classes, "ClassID", "ClassName");
            ViewBag.GradeTypeID = new SelectList(db.GradeTypes, "GradeTypeID", "GradeTypeName");
            //ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentName");
            //ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName");
            return View();
        }

        public JsonResult GetSubjectList(string ClassID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            if (ClassID == "")
            {
                return null;
            }
            else
            {
                List<Subject> SubjectExam = db.ExamSchedules.Where(x => x.ClassId == ClassID).Select(y => y.Subject).ToList();
                return Json(SubjectExam, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult StudentList(string ClassID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            if (ClassID == "")
            {
                return null;
            }
            else
            {
                List<Student> StudentList = db.ClassMembers.Where(x => x.ClassID == ClassID).Select(y => y.Student).ToList();
                return Json(StudentList, JsonRequestBehavior.AllowGet);
            }
        }

       // POST: Grades/Create
       // To protect from overposting attacks, enable the specific properties you want to bind to, for 
       // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
       [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string SubjectID, string[] StudentID, decimal[] GradeOfNumber, string[] Note)//[Bind(Include = "GradeID,StudentID,SubjectID,ExamNumber,GradeOfNumber,note,GradeTypeID,Status")] Grade grade
        {
            if (GradeOfNumber != null && StudentID != null)
            {
               
                    for (int i = 0; i < StudentID.Length; i++)
                    {
                        Grade grade = new Grade();
                        grade.StudentID = StudentID[i];
                        grade.SubjectID = SubjectID;
                        grade.GradeOfNumber = Decimal.Parse(GradeOfNumber[i].ToString());
                        grade.GradeTypeID = 1;
                        var Grade = db.GradeTypes.FirstOrDefault(x => x.GradeTypeID == 1).GradeFail;
                        if (GradeOfNumber[i] > Grade)
                        {
                            grade.Status = true;
                        }
                        else
                        {
                            grade.Status = false;
                        }
                        grade.ExamNumber = 1;
                        grade.note = Note[i];
                        db.Grades.Add(grade);
                        db.SaveChanges();
                    }
                    TempData.Keep();
                    return RedirectToAction("Index");
                
            }
            else
            {
                return View();
            }
        }

        // GET: Grades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            ViewBag.GradeTypeID = new SelectList(db.GradeTypes, "GradeTypeID", "GradeTypeName", grade.GradeTypeID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentName", grade.StudentID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", grade.SubjectID);
            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GradeID,StudentID,SubjectID,ExamNumber,GradeOfNumber,note,GradeTypeID,Status")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(grade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GradeTypeID = new SelectList(db.GradeTypes, "GradeTypeID", "GradeTypeName", grade.GradeTypeID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentName", grade.StudentID);
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", grade.SubjectID);
            return View(grade);
        }

        // GET: Grades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Grade grade = db.Grades.Find(id);
            db.Grades.Remove(grade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZealEducation/Views/Grades/Create.cshtml
@model DataAccess.Grade

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/TableLayout.cshtml";
}
<link href="~/Content/AdminTempale/css2/styleTable.css" rel="stylesheet" />
<!-- Breadcubs Area Start Here -->
<div class="breadcrumbs-area">
    <h3>Grades</h3>
    <ul>
        <li>
            @Html.ActionLink("Back to List", "Index")
        </li>
        <li>Add Grade</li>
    </ul>
</div>
<!-- Breadcubs Area End Here -->
<!-- Class Table Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>Add Grades</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button"
                   data-toggle="dropdown" aria-expanded="false">...</a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                </div>
            </div>
        </div>
        <form action="/Grades/Create" method="post">
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <div class="mg-b-20">
                    <div class="row gutters-8">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="col-lg-4 col-12 form-group">
                            <label>Class Name *</label>
                            <div>
                                @Html.DropDownList("ClassID", null, "-- Select Class --", htmlAttributes: new { @class = " form-control" })
                            </div>
                        </div>
                        <div class="col-lg-1 col-12 form-group"></div>
                        <div class="col-lg-4 col-12 form-group">
                            <label>Subject Name *</label>
                            <div>
                                <select id="SubjectID" name="SubjectID" class="form-control">
                                    <option value="">Select Subject</option>
                                </select>
                                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @*<div class="form-group">
                                @Html.LabelFor(model => model.GradeTypeID, "GradeTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("GradeTypeID", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.GradeTypeID, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                    </div>

                </div>
                <div class="table-responsive">
                    <table id="studentTable" class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    STT
                                </th>
                                <th>
                                    Student ID
                                </th>
                                <th>
                                    Student Name
                                </th>

                                <th>Grade Of Number</th>
                                <th>Note</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                            </tr>
                        </tbody>
                    </table>
                    <script id="ok"></script>
                    <div id="btnSave" class="col-12 form-group mg-t-8">
                        
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Class Table Area End Here -->


<script>
    var Popup, dataTable;
    $(document).ready(function () {
        $("#ClassID").change(function () {
            $.get("/Grades/GetSubjectList", { ClassID: $("#ClassID").val() }, function (data) {
                $("#SubjectID").empty();
                $("#SubjectID").append("<option value=''>-- Select Subject --</option>");
                $.each(data, function (index, row) {
                    $("#SubjectID").append("<option value='" + row.SubjectID + "'>" + row.SubjectName + "</option>");
                })
            })
        })
    })
    $(document).ready(function () {
        $("#SubjectID").change(function () {
            $.get("/Grades/StudentList", { ClassID: $("#ClassID").val() }, function (data) {
                var i = 1;
                $.each(data, function (index, row) {
                    
                    $("#studentTable > tbody").append("<tr><td>"+i+"</td><td>" + row.StudentID + "<input type='text' name='StudentID' value='" + row.StudentID + "' style='display:none;' /></td><td>" + row.StudentName + "</td><td><input type='text'class='decimal form-control' name='GradeOfNumber' value='0' autocomplete='off' /></td><td><input type='text' class='form-control' name='Note' value='' /></td></tr>");
                    i++;
                })
                $("#ok").append("$(function() {$('.decimal').bind('change keyup input', function() {var position = this.selectionStart - 1;var fixed = this.value.replace(/[^0-9\.]/g, '');if (fixed.charAt(0) === '.')fixed = fixed.slice(1);var pos = fixed.indexOf('.') + 1;if (pos >= 0)fixed = fixed.substr(0, pos) + fixed.slice(pos).replace('.', '');if (this.value !== fixed) {this.value = fixed;this.selectionStart = position;this.selectionEnd = position;}});});$( '.decimal' ).blur(function() {if (this.value == '' || this.value == null) {this.value = '0.00';}else if(this.value > 20){this.value = 20;}else{this.value = parseFloat(this.value).toFixed(2);}});");
                $("#btnSave").append("<button type='submit' class='btn-fill-lg btn-gradient-yellow btn-hover-bluedark'>Save</button>")
            })
        })
    })
</script>

ZealEducation/Views/Grades/Edit.cshtml
@model DataAccess.Grade

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Grade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GradeID)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectID, "SubjectID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExamNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExamNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExamNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GradeOfNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GradeOfNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GradeOfNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GradeTypeID, "GradeTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradeTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GradeTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ZealEducation/Views/Grades/Index.cshtml
@model IEnumerable<DataAccess.Grade>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}

<!-- Breadcubs Area Start Here -->
<div class="breadcrumbs-area">
    <h3>Grades</h3>
    <ul>
        <li>
            <a href="#">Home</a>
        </li>
        <li>All TimeTable</li>
    </ul>
</div>
<!-- Breadcubs Area End Here -->
<!-- Student Table Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>All Grades Data</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-expanded="false">...</a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-times text-orange-red"></i>Close
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs text-dark-pastel-green"></i>Edit
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-redo-alt text-orange-peel"></i>Refresh
                    </a>
                </div>
            </div>
        </div>
        <form class="mg-b-20">
            <div class="row gutters-8">
                <div class="col-4-xxxl col-xl-4 col-lg-3 col-12 form-group">
                    <input type="text" placeholder="Search by Name ..." class="form-control">
                </div>
                <div class="col-4-xxxl col-xl-3 col-lg-3 col-12 form-group">
                    <input type="text" placeholder="Search by Class ..." class="form-control">
                </div>
                <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                    <button type="submit" class="fw-btn-fill btn-gradient-yellow">SEARCH</button>
                </div>
                <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                    <a href="@Url.Action("Create", "Grades")" class="btn-fill-lmd radius-30 text-light shadow-dark-pastel-green bg-dark-pastel-green">Create</a>
                </div>
            </div>
        </form>
        <div class="table-responsive">
            <table class="table display data-table text-nowrap">
                <thead>
                    <tr>
                        <th>
                            STT
                        </th>
                        <th>
                            Student ID
                        </th>
                        <th>
                            Student Name
                        </th>
                        <th>
                            Subject Name
                        </th>
                        <th>
                            Grade Of Number
                        </th>
                        <th>
                            Grade Maximum
                        </th>
                        <th>
                            Status
                        </th>
                        <th>
                            Exam Number
                        </th>
                        <th>
                            note
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        var status = @item.Status.ToString();
                        string classStatuss = "";
                        string textStatus = "";


                        <tr>
                            @if (status == "True")
                            {
                                classStatuss = "badge badge-pill badge-success d-block mg-t-8";
                                textStatus = "Passed";
                            }
                            else
                            {
                                classStatuss = "badge badge-pill badge-danger d-block mg-t-8";
                                textStatus = "Fail";
                            }
                            <td>
                                @i
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Student.StudentID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Student.StudentName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Subject.SubjectName)

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GradeOfNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GradeType.GradeMaximum)
                            </td>
                            <td class="@classStatuss">
                                @textStatus
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ExamNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.note)
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Student Table Area End Here -->