ZealEducation/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;

namespace ZealEducation.Controllers
{
    public class ClassesController : Controller
    {
        private ZealEducationMgtDbEntities db = new ZealEducationMgtDbEntities();

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        // GET: Classes
        public ActionResult Index(string search_name)
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            search_name = search_name ?? "";
            var Classs = db.Classes.Where(x => x.ClassName.Contains(search_name)).Include(c => c.Faculty);
            ViewBag.sub = new SelectList(db.Faculties, "FacultyId", "FacultyName");
            return View(Classs);
        }

        // GET: Classs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class Class = db.Classes.Find(id);
            if (Class == null)
            {
                return HttpNotFound();
            }
            return View(Class);
        }

        // GET: Classs/Create
        public ActionResult Create()
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyName");
            return View();
        }
        public List<SelectListItem> getSttus()
        {
            var sttus = new[] {
                new SelectListItem{ Value = "0", Text = "Please Select Gender *" },
                new SelectListItem{ Value = "1", Text = "Đang hoạt động" },
                new SelectListItem{ Value = "2", Text = "Vô hiệu hóa"},
            };
            return sttus.ToList();
        }

        // POST: Classs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClassID,ClassName,status,FacultyID,quantity")] Class Class)
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                db.Classes.Add(Class);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyName", Class.FacultyID);
            return View(Class);
        }

        [HttpGet]
        public JsonResult getByIdToJson(string id)
        {

            if (id != null)
            {
                Class cl = db.Classes.Find(id);
                return Json(new { ClassID = cl.ClassID, ClassName = cl.ClassName, StuQuantityMax = cl.StuQuantityMax, status = cl.Status, FacultyId = cl.FacultyID }, JsonRequestBehavior.AllowGet);
            }
            return Json("Fail", JsonRequestBehavior.AllowGet);
        }
        public JsonResult EditData(Class cla)
        {
            var data = db.Classes.Find(cla.ClassID);
            data.ClassName = cla.ClassName;
            data.StuQuantityMax = cla.StuQuantityMax;
            data.Status = cla.Status;
            data.FacultyID = cla.FacultyID;
            db.SaveChanges();
            return Json("true", JsonRequestBehavior.AllowGet);
        }

        public JsonResult CreateData(Class Class)
        {
            var data = db.Classes.Add(Class);
            db.SaveChanges();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        // GET: Classs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class Class = db.Classes.Find(id);
            var chk_status = 0;
            if (Class.Status == true)
            {
                chk_status = 1;
            }
            else
            {
                chk_status = 2;
            }
            ViewBag.getStatus = new SelectList(getSttus(), "Value", "Text", chk_status);
            if (Class == null)
            {
                return HttpNotFound();
            }
            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyName", Class.FacultyID);
            return View(Class);
        }

        // POST: Classs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClassID,ClassName,status,FacultyID,quantity")] Class Class)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Class).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FacultyID = new SelectList(db.Faculties, "FacultyID", "FacultyName", Class.FacultyID);
            return View(Class);
        }

        // GET: Classs/Delete/5
        public ActionResult Delete(string id)
        {
           
            try
            {
                Class Class = db.Classes.Single(c => c.ClassID.Equals(id));
                db.Classes.Remove(Class);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                TempData["error"] = "delete failed";
                return RedirectToAction("Index");
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZealEducation/Views/Classes/Create.cshtml
@model DataAccess.Class

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/TeacherLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Class</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClassID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.FacultyID, "FacultyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FacultyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FacultyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StuQuantityMax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StuQuantityMax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StuQuantityMax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ZealEducation/Views/Classes/Delete.cshtml
@model DataAccess.Class

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/TeacherLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StuQuantityMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StuQuantityMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Faculty.FacultyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Faculty.FacultyName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ZealEducation/Views/Classes/Details.cshtml
@model DataAccess.Class

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/TeacherLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StuQuantityMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StuQuantityMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Faculty.FacultyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Faculty.FacultyName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClassID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ZealEducation/Views/Classes/Edit.cshtml
@model DataAccess.Class

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/TeacherLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Class</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClassID)

        <div class="form-group">
            @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacultyID, "FacultyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FacultyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FacultyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StuQuantityMax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StuQuantityMax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StuQuantityMax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ZealEducation/Views/Classes/Index.cshtml
@model IEnumerable<DataAccess.Class>

@{
    ViewBag.Title = "Index";
}

<div class="dashboard-content-one">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>All Class</h3>
        <ul>
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>Class</li>
        </ul>
    </div>
    <!-- Breadcubs Area End Here -->
    <!-- All Subjects Area Start Here -->
    <div class="row">
        <div class="col-4-xxxl col-12">
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>New Class</h3>
                        </div>
                        <div class="dropdown">
                            <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                               aria-expanded="false">...</a>

                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs text-dark-pastel-green"></i>Edit
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-redo-alt text-orange-peel"></i>Refresh
                                </a>
                            </div>
                        </div>
                    </div>
                    <form class="new-added-form">
                        <div class="row">
                            <div class="col-12-xxxl col-lg-6 col-12 form-group">
                                <label id="id">Class Id *</label>
                                <input type="text" id="class_Id" class="form-control">
                            </div>
                            <div class="col-12-xxxl col-lg-6 col-12 form-group">
                                <label>Class Name *</label>
                                <input type="text" id="class_name" class="form-control">
                            </div>
                            <div class="col-12-xxxl col-lg-6 col-12 form-group">
                                <label>Quantity *</label>
                                <input type="number" placeholder="" id="quantity" class="form-control">
                            </div>
                            
                            <div class="col-12-xxxl col-lg-6 col-12 form-group">
                                <label>FacultyId</label>
                                @Html.DropDownList("sub", null, "-- select one sub --", new { @class = "form-control" })
                            </div>
                            <div class="col-12 form-group mg-t-8">
                                <button type="button" id="Save" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                                <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-8-xxxl col-12">
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>All Class</h3>
                        </div>
                    </div>
                    <h4>@TempData["error"]</h4>
                    <form class="mg-b-20" action="/Classes/Index" method="get">
                        <div class="row gutters-8">
                            <div class="col-lg-8 col-12 form-group" style="margin-left:60px">
                                <input type="text" placeholder="Search by Subject name ..." class="form-control" name="search_name">
                            </div>
                            <div class="col-lg-2 col-12 form-group">
                                <button type="submit"
                                        class="fw-btn-fill btn-gradient-yellow" id="Search">
                                    SEARCH
                                </button>
                            </div>

                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table display data-table text-nowrap list_sbj" id="list_sbj">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ClassID)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ClassName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.StuQuantityMax)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Faculty.FacultyName)
                                    </th>
                                    
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr id="row">
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassID)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassName)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.StuQuantityMax)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Faculty.FacultyName)
                                        </td>
                                        <td>
                                            <div class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                    <span class="flaticon-more-button-of-three-dots"></span>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" href="@Url.Action("Delete", "Classes", new { id = item.ClassID })">
                                                        <i class="fas fa-times text-orange-red" style="padding-right: 15px"></i>Delete
                                                    </a>
                                                   

                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <script>
//const { type } = require("jquery");

        $(document).ready(function () {
            var checkEdit = false;

            function AjaxCall(url, data, type) {
                return $.ajax({
                    url: url,
                    type: type ? type : 'GET',
                    data: data,
                    contentType: 'application/json'
                });
            };

            $("#Save").click(function () {
                var facuOjb = {
                    ClassID: $("#class_id").val(),
                    ClassName: $("#class_name").val(),
                    quantity: $("#quantity").val(),
                    FacultyId: $("#sub").val()
                };

                if (checkEdit == false) {
                    $.ajax({
                        url: "@Url.Action("CreateData", "Classes")",
                        data: {
                            ClassID: $("#class_Id").val(),
                            ClassName: $("#class_name").val(),
                            StuQuantityMax: $("#quantity").val(),
                            status: $("#Status").val(),
                            FacultyId: $("#sub").val()
                        },
                        type: "POST",
                        success: function (result) {
                            console.log(result);
                            console.log("oke thanh cong");
                            window.location = "https://localhost:44389/Classes";

                        },
                        error: function (e) {
                            alert('class id already exists');
                        }
                    });
                } else {
                    $.ajax({
                        url: "@Url.Action("EditData", "Classes")",
                        data: {
                            ClassID: $("#class_Id").val(),
                            ClassName: $("#class_name").val(),
                            StuQuantityMax: $("#quantity").val(),
                            Status: 1,
                            FacultyId: $("#sub").val()
                        },
                        type: "POST",
                        success: function (result) {
                            console.log(result);
                            console.log("oke thanh cong");
                            window.location = "https://localhost:44389/Classes";

                        },
                        error: function (e) {
                            alert("fail");
                        }
                    });
                }
            });

            $("table tbody #row").click(function () {
                $(this).addClass('selected').siblings().removeClass('selected');
                var value = $(this).find('td:first').html();
                var parseInt = value.replace('\n', '');
                var ac = parseInt.replace('\n', '');
                var id = ac.trim(); 
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("getByIdToJson", "Classes")",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    data: { id: id },
                    success: function (rs) {
                        $("#id").hide(),
                        $("#class_Id").val(rs.ClassID).hide(),
                        $("#class_name").val(rs.ClassName);
                        $("#quantity").val(rs.StuQuantityMax);
                        $("#Status").val(rs.Status);
                        $("#sub").val(rs.FacultyId);
                        checkEdit = true;
                    },
                    error: function (ex) {
                        alert("Fail");

                    }
                });
            });
        });

    </script>