ZealEducation/Controllers/EventTableController.cs
using DataAccess;

using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZealEducationMgt.Controllers
{
    public class EventTableController : Controller
    {
        private ZealEducationMgtDbEntities db = new ZealEducationMgtDbEntities();
        // GET: EventTable
        public ActionResult Index()
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            var result = db.Events.ToList();
            return View(result);
        }

   
        public ActionResult Create()
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event e)
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if (e.startDate <= e.endDate)
                    {
                        e.status = true;
                       db.Events.Add(e);

                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("StartDate", "Start must be lesser than EndTime");
                        ModelState.AddModelError("EndDate", "EndDate must be greater than StartTime");
                    }

                }
                catch
                {
                    return View();
                }
            }
            return View();
        }
        [HttpPost]
        public JsonResult UpdateStatus(int id, bool status)
        {


            var result = db.Events.Find(id);

            if (result != null)
            {

                result.status = status;
                db.Entry(result).State = EntityState.Modified;
                db.SaveChanges();
            }
            return Json(result, JsonRequestBehavior.AllowGet);






        }
        public ActionResult Delete(int? id)
        {
            if (Session["userType"] == null || !Session["userType"].Equals("Staff") && string.IsNullOrEmpty(Convert.ToString(Session["StaffID"])))
            {
                return RedirectToAction("Index", "Login");
            }
            var del = db.Events.Find(id);
            if (del != null)
            {
                db.Events.Remove(del);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        //[Authorize(Roles = "Admin,User")]
        //public ActionResult Edit(int id)
        //{
        //    var result = dbContext.Events.Single(x => x.Event_id == id);
        //    ViewBag.Shop_Id = new SelectList(dbContext.Shops.ToList(), "ShoId", "ShopName", result.Shop_ShoId);

        //    return View(result);

        //}

        //[Authorize(Roles = "Admin,User")]
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, Event e)
        //{
        //    try
        //    {
        //        ViewBag.Shop_Id = new SelectList(dbContext.Shops.ToList(), "ShoId", "ShopName", e.Shop_ShoId);
        //        if (ModelState.IsValid)
        //        {
        //            if (e.StartDate < e.EndDate)
        //            {
        //                Event events = dbContext.Events.Single(x => x.Event_id == id);
        //                events.Shop_ShoId = e.Shop_ShoId;
        //                events.StartDate = e.StartDate;
        //                events.Price = e.Price;
        //                events.Descriptions = e.Descriptions;
        //                events.EndDate = e.EndDate;
        //                events.Image = e.Image;
        //                events.Address = e.Address;
        //                events.Title = e.Title;
        //                events.slug = e.slug;
        //                events.Meta_title = e.Meta_title;
        //                events.Meta_keyword = e.Meta_keyword;
        //                events.Meta_description = e.Meta_description;
        //                events.ModifiedDate = DateTime.Now;
        //                events.Status = e.Status;
        //                dbContext.SaveChanges();
        //                return RedirectToAction("Index");
        //            }
        //            else
        //            {
        //                ModelState.AddModelError("StartDate", "Start must be lesser than EndTime");
        //                ModelState.AddModelError("EndDate", "EndDate must be greater than StartTime");
        //            }
        //        }

        //    }
        //    catch
        //    {
        //        return View(e);
        //    }

        //    return View(e);
        //}

        //[Authorize(Roles = "Admin,User")]
        //public ActionResult Delete(int id)
        //{
        //    var result = dbContext.Events.Single(x => x.Event_id == id);
        //    ViewBag.Shop_Id = new SelectList(dbContext.Shops.ToList(), "ShoId", "ShopName", result.Shop_ShoId);
        //    return View(result);
        //}

        //[Authorize(Roles = "Admin,User")]
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, Shop s)
        //{
        //    try
        //    {
        //        var result = dbContext.Events.Single(x => x.Event_id == id);
        //        dbContext.Events.Remove(result);
        //        dbContext.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View(s);
        //    }
        //}
    }
}

ZealEducation/Views/EventTable/Create.cshtml
@model DataAccess.Event

@{
    ViewBag.Title = "Create";
}
<div class="breadcrumbs-area">
    <h3>Event</h3>
    <ul>
        <li>
            @Html.ActionLink("Back to List", "Index")
        </li>
        <li>Add Event</li>
    </ul>
</div>
<!-- Breadcubs Area End Here -->
<!-- Admit Form Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>Add New Event</h3>
            </div>

        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal new-added-form">
                <div class="row">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        @Html.LabelFor(model => model.EventName)
                        <div>
                            @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
                        </div>
                    </div>




                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        @Html.LabelFor(model => model.startDate)
                        <div>
                            @*@Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control" } })*@
                            <input type="text" id="startDate" name="startDate" placeholder="dd/mm/yyyy" class="form-control air-datepicker DayTimeTbl"
                                   data-position='bottom right'>
                            <i class="far fa-calendar-alt"></i>
                            @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        @Html.LabelFor(model => model.endDate)
                        <div>
                            @*@Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control" } })*@
                            <input type="text" id="endDate" name="endDate" placeholder="dd/mm/yyyy" class="form-control air-datepicker DayTimeTbl"
                                   data-position='bottom right'>
                            <i class="far fa-calendar-alt"></i>
                            @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="col-xl-3 col-lg-6 col-12 form-group">
                        @Html.LabelFor(model => model.note)
                        <div>
                            <textarea class="form-control" name="note" rows="3" placeholder="Note..."></textarea>

                            @*@Html.EditorFor(model => model.TimeOut, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="col-12 form-group mg-t-8">
                        <button type="submit" value="Create" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                        <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                    </div>
                </div>
            </div>
        }

    </div>
</div>


@section Scripts{

    <script src="~/Content/assets/js/ab.js"></script>
    <script>


        $(document).ready(function () {


            $('#startDate').flatpickr({
                minDate: "today",

                dateFormat: "d-m-Y",
            });
            $('#endDate').flatpickr({
                minDate: "today",

                dateFormat: "d-m-Y",
            });
        })


    </script>

}

ZealEducation/Views/EventTable/Index.cshtml
@model IEnumerable<DataAccess.Event>
@{
    ViewBag.Title = "Index";
}
@section Styles{

    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

            .switch input {
                opacity: 0;
                width: 0;
                height: 0;
            }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

            .slider:before {
                position: absolute;
                content: "";
                height: 26px;
                width: 26px;
                left: 4px;
                bottom: 4px;
                background-color: white;
                -webkit-transition: .4s;
                transition: .4s;
            }

        input:checked + .slider {
            background-color: #40b754;
        }

        input + .slider {
            background-color: red;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

            .slider.round:before {
                border-radius: 50%;
            }
    </style>
}
<div class="dashboard-content-one">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>Event</h3>
        <ul>
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>All Event</li>
        </ul>
    </div>
    <!-- Breadcubs Area End Here -->
    <!-- Teacher Table Area Start Here -->
    <div class="card height-auto">
        <div class="card-body">
            <div class="heading-layout1">
                <div class="item-title">
                    <h3>All Event Data</h3>
                </div>

            </div>
            <form class="mg-b-20">
                <div class="row gutters-8">

                    <div class="col-2-xxxl col-xl-3 col-lg-3 col-12 form-group">

                        <a href="@Url.Action("Create","EventTable")" class="btn btn-success fw-btn-fill" role="button" style="min-width:110px">Add Event</a>
                    </div>
                </div>
            </form>
            <div class="table-responsive">
                <table class="table display data-table text-nowrap">
                    <thead>
                        <tr>
                            <th hidden>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input checkAll">
                                </div>
                            </th>
                            <th>EventID</th>
                            <th>
                                EventName
                            </th>
                            <th>
                                startDate
                            </th>
                            <th>
                                endDate
                            </th>

                            <th>
                                status
                            </th>
                            <th>note</th>

                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td hidden>
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input">
                                    </div>
                                </td>
                                <td>@item.EventID</td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EventName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.startDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.endDate)
                                </td>
                                <td>
                                    <label class="switch">
                                        <input type="checkbox" class="toggle-checkbox" data-id="@item.EventID" @(item.status ? "checked" : "")>
                                        <span class="slider round"></span>
                                    </label>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.note)
                                </td>


                                <td>
                                    @Html.ActionLink("Delete", "Delete", new { id = item.EventID }, new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Teacher Table Area End Here -->

</div>
@section scripts{
    <script type="text/javascript">
    var url = '@Url.Action("UpdateStatus")';
    $('.toggle-checkbox').click(function () {

        var isChecked = $(this).is(':checked'); //CheckBox checked - True or false
        var id = $(this).data('id'); //Get the id of that specific checked row

        $.post(url, { id: id, status: isChecked }, function (response) {
            if (!response.result) {

                toastr.success('Create successful!', 'Success!', {
                    closeButton: true,
                    tapToDismiss: false
                });

            } else {
                toastr.error('Create failed!', 'Error!', {

                    closeButton: true,
                    tapToDismiss: false
                });
            }
        })
    });
    </script>
}